### ISSUE TITLE
Rust, Elixir e ELM: I vostri prossimi linguaggi preferiti

### ISSUE THREAD

**Issue by alepore** [DevMarche/eventi#10]
Rust, Elixir e ELM: Una panoramica (non troppo) tecnica.

Parliamo insieme (interazione di qualsiasi tipo benvenuta!) di questi tre linguaggi moderni, affidabili, con community attive che coprono una grossa percentuale delle esigenze odierne. 
Non giocattoli "cool" ma soluzioni vere e probabilmente migliori (!) di quelle che usiamo tutti i giorni.

(Techbar, 2018)

**Comment by ste8** [comment]
Ciao @alepore , intendi che potresti "guidare" tu l'incontro parlando di questi linguaggi, o cerchi persone con cui poterne parlare?

E sarebbe un incontro solo o più incontri (es. uno per linguaggio)?

**Comment by alepore** [comment]
Ciao, sarebbe un incontro solo (appunto introduttivo, niente di in-depth).
Il talk lo farei io, volevo solo dire che qualsiasi integrazione/replica sarebbe ben accetta dato che certi concetti potrebbero rientrare nel campo delle opinioni.

**Comment by guizzardi** [comment]
Io sto studiando Rust e probabilmente mi avvicinerò anche a GO... potrei portare qualche argomento...

**Comment by alepore** [comment]
@guizzardi sicuramente benvenuto!
Anche Go era papabile ma se ne è già parlato in una serata dedicata.

**Comment by ilkosta** [comment]
ciao ho usato Rust tanto tempo fa... Elm lo trovo fantastico. Non vedo l'ora.

**Comment by alepore** [comment]
Chiudo in quanto era stato proposto quasi due anni fa e ho un po perso di vista gli argomenti...
