### ISSUE TITLE
PHP Test Fest 

### ISSUE THREAD

**Issue by Fuminshou** [DevMarche/eventi#11]
Il GrUSP partecipa al PHP Test Fest (da settembre a dicembre) e offre una cassa della sua birra ai PUG che partecipano all'evento.

Può interessarvi partecipare come simil-PUG?
DevRomagna sta valutando la proposta per una serata a dicembre: potrebbe essere interessante un gemellaggio?

Dal GrUSP chiedono conferma quanto prima per organizzarsi con le birre.

Tutte le info sull'evento qui: https://phptestfest.org/start/
I gruppi già attivi: https://phptestfest.org/groups/2017/

**Comment by DonCallisto** [comment]
Io sarei interessato a partecipare, come già espresso in forma privata.

**Comment by ste8** [comment]
ciao @Fuminshou , data l'urgenza, potresti scrivere un post anche sul gruppo fb di DevMarche, linkando quest'issue? li probabilmente lo leggono più persone.

**Comment by ste8** [comment]
@Fuminshou non sono programmatore PHP, ma se posso dare una mano nella logistica per un evento in gemellaggio con DevRomagna, volentieri!

Nicola era già stato ad un evento python al Warehouse Coworking Factory a Marotta, che potrebbe essere una location a metà (se consideriamo nell'altro estremo città come San Benedetto del Tronto).
Se vi potrebbe piacere come location, posso sentirli.
Se invece preferite qualcosa un po' più a nord, possiamo sondare il terreno.

**Comment by Fuminshou** [comment]
Grazie @ste8 ma Ideato a Cesena mette già la sede per l'evento Romagnolo.
La mia idea era più quella di fare 2 eventi a distanza di qualche giorno in modo che chi vuole può partecipare ad entrambi oppure scegliere il più comodo per lui. E sponsorizzarci a vicenda, ovviamente.
Non so da voi una sede comoda quale può essere, io posso sentire il cowo di osimo

**Comment by ste8** [comment]
ok! sì, Ancona e dintorni (quindi Osimo compreso) è la zona più facilmente raggiungibile nelle Marche, quindi anche il cowo42 andrebbe benissimo.

**Comment by ste8** [comment]
@Fuminshou quindi provi tu ad occuparti della sala? c'è da darti una mano in qualche modo a livello organizzativo?
@DonCallisto tu saresti disponibile a dare una mano?

**Comment by DonCallisto** [comment]
@ste8 se c'è da coordinarsi con qualcuno per meglio capire come si organizza un TestFest non c'è problema. Comunque, @Fuminshou organizzandolo anche a Cesena, probabilmente avrà già un'idea chiara di come portare avanti le cose una volta parlato con il referente italiano. Possiamo eventualmente coordinarci tra noi una volta che lei ha le idee chiare di come procedere.

Per te è ok @Fuminshou?

**Comment by Fuminshou** [comment]
Il cowo42 è disponibile ad ospitare l'evento 👍 
Non appena chiariamo come registrarci col grusp (se pug singoli o unitamente) vi aggiorno sull'evento.

**Comment by Fuminshou** [comment]
Ho parlato con Matteo Beccati del GrUSP, mi ha detto che l'evento in una sola serata non si riesce a far l'evento (serve tempo per decidere cosa fare ed eventualmente dividersi in sottogruppi).
Gli altri PUG lo hanno fatto di sabato, potremmo farlo anche noi, dalle 10:30 alle 17:30 (o finchè si regge).
Il giorno potrebbe essere il 2/12 (in contemporanea con devRomagna così facciamo gruppo)

**Comment by DonCallisto** [comment]
Cerchiamo di capire quanti interessati ci sono e sopratutto se c'è un tutor in grado di portare avanti questa cosa, altrimenti vedo inutile frammentare l'evento in due tra DevMarche e DevRomagna e ne farei uno unico "in collaborazione".

**Comment by Fuminshou** [comment]
Come funziona l'adesione qui? Come capire se un evento interessa o no?
@DonCallisto perchè parli di tutor? I gruppi si organizzano da soli, serve qualcuno che si occupi della logistica al massimo

**Comment by ste8** [comment]
Per capire se un evento può interessare conviene aprire una discussione sul gruppo fb di DevMarche.
Al momento non stiamo usando i like sulle issue qui in github.

**Comment by DonCallisto** [comment]
@Fuminshou ci vuole qualcuno che sappia come procedere, un "mentore" diciamo che sappia indicare agli altri qual è la procedura corretta da seguire. Io non l'ho mai fatto quindi dovrei studiare la cosa. Se qualcuno conosce già le modalità, quello può essere "un tutor" (o mentore come lo chiamano loro)

**Comment by Fuminshou** [comment]
@ste8 il mio post sul vostro gruppo ha attirato 5 like (di cui uno tuo e uno di samuele). Cosa mi suggerisci, lo ricondivido?

@DonCallisto la loro sezione mentors ha solo 4 nomi di gente non italiana che al massimo potrebbe supportarci da remoto (fuso orario permettendo). Le loro linee guida per l'organizzare l'evento parlano di un meeting iniziale per spiegare come contribuire al PHPtestfest, decidere se il gruppo lavoro unito (e quindi scegliere cosa testare) oppure se ogni partecipante decide in autonomia.
Io sarò all'evento di cesena, quindi capiamo se vale la pena farlo anche nelle marche, e se tra i partecipanti c'è qualcuno che può tenere le fila del discorso.

**Comment by DonCallisto** [comment]
> Le loro linee guida per l'organizzare l'evento parlano di un meeting iniziale per spiegare come contribuire al PHPtestfest

Questo è già un punto oscuro: per questo intendevo dire che se qualcuno sa/ha esperienza in merito, sarebbe ottimo segnalarlo per capire se ce ne fossero almeno due di queste figure (una marche, una romagna).
Altrimenti la mia paura è quella di avere una frammentazione (parlo per noi Marche) e sopratutto incontrarsi e non riuscire a tirare le fila per mancanza di cognizione di ciò che dovrà essere fatto.

**Comment by ste8** [comment]
@Fuminshou si potrebbe scrivere un nuovo post sul gruppo fb, indicando sia la data, sia di scrivere un commento esplicito se si è interessati a partecipare.

Non so se possa valer la pena scrivere un messaggio anche nel "vecchio" google group del PUG Marche: https://groups.google.com/forum/#!forum/pugmarche

**Comment by Fuminshou** [comment]
@ste8 fatto su fb, sul gruppo di pug marche sto aspettando l'accesso

**Comment by Fuminshou** [comment]
'giorno
su facebook, tolto @DonCallisto che ha una voglia matta di salire a cesena :), abbiamo una ragazza che ci prova e uno taggato in un commento che chissà chi è, chissà se c'è

Direi che per una persona e mezzo non vale la pena duplicare l'evento... a meno che voi non abbiate ricevuto altri feedback

**Comment by DonCallisto** [comment]
Direi che non ha senso duplicare l'evento a questo punto.
Per altro io per Sabato potrei avere un problema, poi eventualmente te lo comunico in settimana @Fuminshou

**Comment by ste8** [comment]
da quest'altro post https://www.facebook.com/groups/developermarche/permalink/1874963345877449/  sembra che interesse per PHP ci sia, mentre questo specifico evento non ha riscosso molta attenzione.

**Comment by ste8** [comment]
@Fuminshou questo issue conviene chiuderlo ormai? O pensi possa essere ancora utile?

**Comment by Fuminshou** [comment]
@ste8 yes, chiusa ;)
