### ISSUE TITLE
Deploy with Git : for poor and business developer

### ISSUE THREAD

**Issue by rokity** [DevMarche/eventi#12]
Mettere in produzione software tramite git hooks , alias ,git credentials storie ed altri tricks.
Sia per ambienti aziendali che per sviluppatori senza soldi .

**Comment by Nemolo** [comment]
Sarei molto interessato

**Comment by rokity** [comment]
Stavo pensando che si potrebbe realizzare o un workshop in cui si configurano 3 ambienti di sviluppo, oppure un live in cui lo faccio mentro lo spiego.

**Comment by ste8** [comment]
@Nemolo potresti essere disponibile ad organizzare l'evento?

**Comment by Nemolo** [comment]
@ste8  non ho idea di cosa comporti essere un organizzatore... ti contatto via messaggio per capire meglio

**Comment by DGuidi** [comment]
guarda, un'idea la trovi [qui](http://dev.marche.it/organizza-un-evento/)

**Comment by bizcomit** [comment]
anche qui, trovo molto interessante il tema (sul quale personalmente sono poco ferrato) 
come location rendo disponibile coworking ancona

**Comment by rokity** [comment]
Settembre ce l'ho infuocato pieno di impegni. Per me sarebbe meglio verso Ottobre se non Novembre.
Scusami ma per me è un periodo di Tesi e Laurea in quel periodo.

**Comment by nonno** [comment]
@rokity settembre è giunto e ottobre è alle porte, butti giù una serie di date tra ottobre e novembre così mettiamo a calendario?

**Comment by ste8** [comment]
nella seconda metà di ottobre probabilmente faremo il secondo incontro sulla blockchain - vediamo intanto come va stasera il primo :) - questo è fattibile nella prima metà di novembre?

**Comment by rokity** [comment]
Potremmo farlo agli inizi di novembre se a voi va bene. O nella fine di ottobre o i primi primissimi di novembre. Potremmo farla la settimana tra il 22 e il 26? La settimana dopo io non ci sono. Oppure il 5 o il 6 novembre ?

**Comment by nonno** [comment]
@rokity il 6 novembre credo sia semplicemente perfetto. @bizcomit il CowoAncona sarebbe disponibile per quella data?

**Comment by nonno** [comment]
@rokity per il 6 abbiamo il benestare di tutti e possiamo farlo al Coworking di Ancona. Mettiamo in agenda?

**Comment by rokity** [comment]
Penso che solo @ste8 può farlo o sbaglio?

**Comment by nonno** [comment]
Ni, se tu ci dai la disponibilità è in agenda visto che sta bene a tutti e quella data è libera (e suggerita proprio da Stefano). Poi a inizio ottobre creiamo l'evento e pubblicizziamo, se vuoi ti posso dare una mano io.

**Comment by rokity** [comment]
Per me va benissimo il 6 novembre, la confermo. Si nella pubblicizzazione se mi dai un mano sarei più che contento. Poi sulla presentazione quando ho un minuto li bero la butto giù e te la condivido cosi che mi dai dei consigli e cosi via, che ne pensi?

**Comment by nonno** [comment]
Perfetto, accendiamola. Lo dico agli altri e confermo a Roberto Caporale che il Coworking quella sera ci serve (mi aveva già dato la disponibilità qualche giorno fa). E spostiamo la conversazione su canali più tranquilli di questa pagina :)

**Comment by nonno** [comment]
Video dell'evento:
https://vimeo.com/299394122

Slide:
https://docs.google.com/presentation/d/1Hr0lxQstLXijo_Lq4QMJVJz5vxUgzN0EW16MFxcB5lM/edit?fbclid=IwAR2MZufDTFKaz7BySk9-UBSkGpvX9o1e5SwIsV66GuzTS2-aP1rx74ywWog#slide=id.p

Repository:
https://github.com/rokity/ContinuousDeploymentWithGit
