### ISSUE TITLE
[PHP / DEVOPS] Scaling PHP apps

### ISSUE THREAD

**Issue by ghost** [DevMarche/eventi#14]
L'evoluzione di un'applicazione web è spesso sorprendente: utenti e funzionalità crescono (per fortuna!) in modo imprevisto e ti ritrovi problemi inaspettati. La tua app richiede uno o due server per funzionare e poi... picchi di accessi, milioni di richieste web al giorno, database che sembra esplodere, file che non sai più dove mettere. L'applicazione rallenta, inizi a diventare il miglior amico del comando `top` e ti affidi alla speranza che i core bastino ed il db non si blocchi. No, la soluzione non è aumentare core e ram. Vedremo insieme come è possibile far scalare senza limiti un'applicazione PHP: dalle richieste web al database, dalle sessioni al filesystem fino ad arrivare ai tasks asincroni.

Useremo Symfony come framework ma i riferimenti ad esso sono davvero minimi e quindi tutto quello che verrà detto vale per qualsiasi altro framework o per applicazioni scritte in plain PHP.

Prenderemo spunto da un talk che ho fatto al Symfony day 2016 a Roma.

Dalle 19.30 alle 20 faremo cena insieme con pizza e bibite. Sarà l'occasione per fare un po' di networking!

Alle ore 20 inizia il talk, della durata di circa 1h / 1h30m. Al termine domande e approfondimenti a richiesta.

L'evento è gratuito e la pizza è offerta da Madisoft. Vi chiedo tuttavia la cortesia di prendere il biglietto (e comunicare se non potete piu venire una volta preso) al fine di poter comprare la giusta quantità di pizza.

Evento: https://www.eventbrite.com/e/scaling-php-apps-tickets-41382089945

**Comment by ste8** [comment]
Evento fatto il 09/01/2018.
Slide: https://www.slideshare.net/matteomoro8/scaling-php-apps
