### ISSUE TITLE
[ActorModel - Akka.net] a lightweight introduction to a scalable programming model

### ISSUE THREAD

**Issue by AGiorgetti** [DevMarche/eventi#18]
La programmazione multiprocessing / multithreading introduce delle complessità, ma 'fare più cose contemporaneamente' è un ottimo modo per 'scalare' le nostre applicazioni migliorandone responsività e performance globali.

Come farlo in modo 'semplice' ? Cosa è un Actor Framework ? Quali problemi affronta e quali risolve ?

Nel mondo .NET uno di questi strumenti è Akka.net, porting di Akka nato nel mondo Java/Scala.

Direi che una chiacchierata serale potrebbe essere interessate

**Comment by melkio** [comment]
Connects to #4  :)

**Comment by AGiorgetti** [comment]
Si, è giusto per dire che oltre al 'full day' possiamo farci una chiacchierata più informale una sera, magari meno spinta

**Comment by ste8** [comment]
Video dell'evento: 
https://vimeo.com/album/5006034

Slide:
1. https://www.slideshare.net/StefanoDelFuria/akkanet-actor-model
2. https://www.slideshare.net/melkio/cooking-akkanet-and-azure-service-fabric-together
3. https://www.slideshare.net/giorgettialessandro/the-big-picture-integrating-buzzwords
