### ISSUE TITLE
[ActorModel - Akka.Remoting / Akka.Cluster] E se una sola macchina non ci bastasse più?

### ISSUE THREAD

**Issue by AGiorgetti** [DevMarche/eventi#19]
E se dopo aver ottimizzato la nostra applicazione per usare tutti i core possibili ed immaginabili della nostra CPU... tutto questo non fosse abbastanza?

E' il momento di distribuire la soluzione su più macchine.

E qui le cose si complicano....

ce la facciamo un'altra chicchierata serale ?

**Comment by melkio** [comment]
Connects to #4

**Comment by ste8** [comment]
Video dell'evento: 
https://vimeo.com/album/5006034

Slide:
1. https://www.slideshare.net/StefanoDelFuria/akkanet-actor-model
2. https://www.slideshare.net/melkio/cooking-akkanet-and-azure-service-fabric-together
3. https://www.slideshare.net/giorgettialessandro/the-big-picture-integrating-buzzwords

**Comment by AGiorgetti** [comment]
se vogliamo anche farci un techbar serale con del codice io sono a disposizione.
