### ISSUE TITLE
WebAssembly

### ISSUE THREAD

**Issue by DGuidi** [DevMarche/eventi#20]
prendo spunto dall'abstract della sessione che andrea agnoletto proporrà al prossimo [XE Community Meeting](http://www.xedotnet.org/eventi/electron-night/) e che copio qui sotto:

"
**WebAssembly: what is it?**
In questa sessione daremo insieme una prima occhiata a quello che potrebbe diventare un "disruptive change" nel mondo dello sviluppo Web. Capiremo che cos'è WebAssembly partendo dal basso, cioè dal suo bytecode e dalla sua architettura di base, per poi salire andando ad esplorare le possibili opportunità d'impiego per i linguaggi/framework di alto livello. Vedremo con degli esempi "live" installazione ed uso delle principali SDK ad oggi a dispozione in modo da fornire tutti gli strumenti necessari per inziare a cimentarsi con la programmazione nel nuovo mondo di WebAssembly.
"

mi piacerebbe che qualcuno che abbia un pò di competenza in merito ne parlasse, magari proprio andrea (qualcuno lo conosce? ha account github che posso "aggiungere" almeno per notificargli la cosa?) in streaming/hangout, oppure altri.

direi formato techbar: una cosa molto easy e poco impegnativa. non so se l'argomento si presta anche ad un paio di lightning talk, in effetti...

**Comment by DGuidi** [comment]
ho intanto notificato gli amici della XE Community che "sono stati nominati"

**Comment by andrea-agnoletto** [comment]
Ciao Diego, se trovate interessante l'argomento mi propongo volentieri per portare la mia sessione.

**Comment by DGuidi** [comment]
spostato tutto sulla #21
