### ISSUE TITLE
[Mobile-Ionic-Nativescript] Sviluppare applicazioni mobile con Angular e Typescript: NativeScript vs Ionic

### ISSUE THREAD

**Issue by apomic80** [DevMarche/eventi#24]
Dopo aver investito su Angular per lo sviluppo web, possiamo riutilizzare quanto imparato per sviluppare app mobile per iOS e Android? La risposta è si e possiamo scegliere, sulla base dei nostri requisiti, tra realizzare una app nativa con NativeScript o ibrida con Ionic. Vedremo insieme potenzialità e limiti di entrambi gli approcci, cercando di capire quando scegliere uno piuttosto che l'altro, con un approccio molto pratico.

**Comment by matteo-pica** [comment]
Ciao Sarei interessato a partecipare all'evento. Non ho esperienza per fare l'organizzatore. Spero di non essere off topic

**Comment by ste8** [comment]
@matteo-pica se ti va di provare ad organizzare l'evento, non è una cosa complicata... non dobbiamo fare una cosa perfetta, tanto nessuno ci paga :)

molti di coloro che hanno organizzato gli ultimi workshop erano alla loro prima esperienza, e sono riusciti a farlo senza particolari problemi, dandoci un po' di supporto a vicenda.

**Comment by Defkon1** [comment]
http://dev.marche.it/eventi/2018/11/06/angular-and-beyond-ancona-7-dicembre-2018/
