### ISSUE TITLE
Intrudizione a Reason 

### ISSUE THREAD

**Issue by lorenzo-pomili** [DevMarche/eventi#25]
**Abstract**
Reason è un linguaggio sviluppato dal team di Facebook. Il paradigma funzionale può aiutarci a risolvere alcuni problemi legati alla grande complessità di alcune attuali applicazioni frontend.
Reason è un linguaggio multiparadigma con una forte predisposizione al funzionale.
Vediamo come muovare i primi passi nell'utilizzo di questo linguaggio.

**Periodo**
Aprile

**Comment by nonno** [comment]
Pensi al techbar? Credi ci sia speranza di fare un workshop unico magari con altre sessioni sul paradigma funzionale? Nel caso hai già un'idea sul dove farla (tipo e-xtrategy) o stai valutando anche l'idea del webinar?

**Comment by lorenzo-pomili** [comment]
Per ora pensavo di fare un talk live (probabilmente al Cowo42), non più lungo di 1 ora, però sono aperto ad altre proposte

**Comment by nonno** [comment]
Butta là un ventaglio di date che credi ti potrebbero andar bene, così sentiamo in quale il Cowo è libero ed evitiamo collisioni. Non mi pare ci siano altre proposte di sessioni sul paradigma funzionale, quindi un techbar serale da un'oretta con eventuale tempo a seguire per pasticciare ci sta benissimo.

**Comment by nonno** [comment]
Il dado è tratto: giovedì 26 aprile, Cowo 42

**Comment by nonno** [comment]
Video dell'evento:
https://vimeo.com/268088244
