### ISSUE TITLE
Mutation testing

### ISSUE THREAD

**Issue by mazzcris** [DevMarche/eventi#26]
Ciao,
mi piacerebbe parlare di mutation testing: cos'è, a cosa serve e quali sono i tool/framework a supporto per PHP e JS.
Sarebbe un talk di 1 oretta con qualche esempio pratico.

**Comment by ste8** [comment]
In calendario due serate, 6 e 20 marzo 2019, per parlare di testing
/cc @Defkon1

**Comment by ste8** [comment]
Evento organizzato, video: https://vimeo.com/334926233
