### ISSUE TITLE
Blockchain ne abbiamo?

### ISSUE THREAD

**Issue by guizzardi** [DevMarche/eventi#27]
Propongo un techbar per parlare di questa tecnologia ed eventuali progetti che potrebbero essere realizzati. Si può dividere la serata in due parti, una prima introduzione/rispolvero di cosa sia Blockchain e una seconda parte dove proporre e analizzare idee.

**Comment by pleopardi** [comment]
Parlando di implementazioni, almeno qualche accenno più pratico ad Ethereum e Hyperledger Fabric non sarebbe male!

**Comment by ste8** [comment]
Video: https://vimeo.com/290167121
