### ISSUE TITLE
[Capture the flag] - Ti andrebbe (di giocare a) Guerra Termonucleare Globale?

### ISSUE THREAD

**Issue by Illogico** [DevMarche/eventi#28]
In computer security, il rubabandiera (meglio conosciuto con il nome originale inglese Capture the Flag) è un gioco di hacking dove team o singoli cercano vulnerabilità in sistemi e software messi a disposizione dagli organizzatori della competizione al fine di sfruttarle e di collezionare le varie flag (bandiere) nascoste sul sistema bersaglio.
Programma:
- introduzione (15-20 minuti)
- teoria (30-45 minuti)
- pratica (30-60 minuti)
Chi vuole partecipare dovrebbe dotarsi di un portatile e una penna USB (da cui fare il boot con una Kali Linux live, consigliata almeno da 8GB)

**Comment by jackcoral89** [comment]
Figo ! Maggiori informazioni ??

**Comment by ste8** [comment]
Sarebbe una sfida tra team o ognuno "gioca" singolarmente?

**Comment by Illogico** [comment]
Maggiori informazioni: root-me.org , vulnhub.com
"nostro canale Telegram": https://t.me/joinchat/Ab9jU0ogKA4ZaEqqvDCuCw
Modalità di gioco: "solo", coop, tutti vs tutti o anche a squadre ovviamente per le versioni più complesse (tipo: multi host con automatismi per la gestione punteggi) sarà più complessa anche la preparazione

**Comment by subm0ther** [comment]
Ci sono!

**Comment by Defkon1** [comment]
ci sono limiti per quanto riguardo il numero di partecipanti (massimo/minimo)?
richieste particolari in termini di risorse che devono essere disponibili durante l'evento (es. connettività)?

**Comment by qina83** [comment]
@illogico sei ancora interessato ad organizzare il gioco con noi?

**Comment by Illogico** [comment]
"Si può fare" (cit).. quanto tempo abbiamo?

Ciao
Nick

Il 26 Settembre 2019 20:00:37 CEST, cristiano giulioni <notifications@github.com> ha scritto:

**Comment by qina83** [comment]
Stiamo organizzando un evento per Novembre. Il giorno lo possiamo decidere insieme.
Ho bisogno di sapere cosa serve come infrastruttura e che limiti abbiamo (tipo il numero di giocatori / partecipanti).

Un incontro tipo "cena con pizza e dopo cena" stile techbar ci da un paio d'ore buone di attività

**Comment by qina83** [comment]
Segnatevi il 28 novembre....

**Comment by ste8** [comment]
Materiale dell'evento: https://vimeo.com/showcase/6619179
