### ISSUE TITLE
Stranger Streams

### ISSUE THREAD

**Issue by andreabalducci** [DevMarche/eventi#3]
![image](https://user-images.githubusercontent.com/212729/31987075-eecfdf0e-b96a-11e7-86e7-2e7e33a7fe08.png)

Abbiamo scritto un eventstore da zero, forti dell'esperienza in produzione fatta negli ultimi 4 anni.

Perché? 

1. Ora possiamo far girare il nostro codice su linux, windows, ios, android, mac.
2. Il sistema è ottimizzato per i pattern di utilizzo tipici di un eventstore
3. Flessibile quanto basta
4. Tagliato via tutto quello che non è fondamentale per un commit log ed aggiunti gli entry point per poter configurare il tutto
5. Volevamo un codice espressivo che potesse fungere anche da documentazione

In questo evento vorrei raccontare le problematiche e le scelte tecniche che hanno portato allo sviluppo dell'eventstore, 5 slide e il resto codice alla mano.

**Comment by Defkon1** [comment]
molto interessato

**Comment by andreabalducci** [comment]
Location: Cowo42 (come backup Cowo Ancona)

**Comment by nonno** [comment]
Se il posto c'è già e lo proporrai già a Napoli l'organizzazione dovrebbe andare via liscia e senza intoppi, quindi forse è il caso che ci provi qualcuno che non l'ha mai fatto. Se però non si propone nessuno me ne occupo io, o al più do una mano all'eventuale novizio che ci vuol provare ma non è sicuro.

**Comment by Defkon1** [comment]
che formato/durata avevi in mente?

**Comment by nonno** [comment]
Bisognerebbe metterci una label in effetti, purtroppo ancora lo può fare solo l'amministratore ma ci organizzeremo. @Defkon1 in questo caso Andrea non l'ha specificato perché credo dia per scontato che sarà un techbar serale di un paio d'ore con pizza.

**Comment by andreabalducci** [comment]
ho già chiesto a @ste8 di metterci la label TechBar.
Roba easy, altrimenti serve una settimana per spiegare tutto il fumo che c'e' sotto

**Comment by valerionarcisi** [comment]
Bello!

**Comment by Defkon1** [comment]
Io una mano a organizzare la posso dare (tanto mi pare che il più è fatto), ma per me novembre è un mese completamente out... pensavi di tenere il techbar questo mese?

**Comment by andreabalducci** [comment]
idem, novembre tra nuovi membri del team e due progettoni è già sold-out, potremmo fare inizio dicembre così il tutto è già rodato visto che il 23 lo porto a Napoli.

**Comment by Defkon1** [comment]
ok, per dicembre se ne può parlare... :-)

**Comment by nonno** [comment]
@Defkon1 ci pensi tu quindi a portare avanti la cosa? Intendo ragionare sulle date con Andrea evitando sovrapposizioni con altri eventi, sentire se nelle date papabili il Cowo42 è disponibile, ... dai che almeno mettiamo la label "organizzazione in corso" :)
Qui più o meno le informazioni ci dovrebbero essere tutte: http://dev.marche.it/organizza-un-evento/
Poi in caso se hai dubbi o ti serve una mano puoi sempre chiedere. In genere almeno due settimane prima della data scelta sarebbe bene pubblicare l'evento.

**Comment by Defkon1** [comment]
ok, che date avevate in mente? per me l'unica data out al momento è il 13/12

**Comment by ste8** [comment]
a dicembre giorni come il 5, 6, 12 o 14?

**Comment by Defkon1** [comment]
il 12 per me sarebbe l'ideale...

**Comment by ste8** [comment]
@andreabalducci @Defkon1 confermiamo martedì 12 dicembre (sera) come data?

**Comment by Defkon1** [comment]
per me può andare, non so @andreabalducci come è messo...

**Comment by andreabalducci** [comment]
ok per il 12

**Comment by Defkon1** [comment]
dopo discussione con @andreabalducci abbiamo infine scartato il 12/12 e stiamo convergendo sul 5/12... @ste8 ci sono sovrapposizioni per quella data?

**Comment by ste8** [comment]
Il 5/12 io ho già un impegno, ma in generale non dovremmo avere particolari collisioni con altri eventi, almeno locali.
Per me procedete pure con quella data.

**Comment by Defkon1** [comment]
ok, ieri ho inviato un messaggio linkedin a Roberto del Coworking Ancona per capire se loro possono ospitare... qualora non mi rispondesse (magari non controlla spesso linkedin) abbiamo contatti più diretti?

**Comment by andreabalducci** [comment]
eravamo d'accordo di farlo al Cowo42.

**Comment by Defkon1** [comment]
ok, ho quindi già fatto il mio primo danno da neo-organizzatore... :-(

mi giri un contatto del CoWo42 così mi faccio confermare la disponibilità per il 5/12?

**Comment by Defkon1** [comment]
altra domanda @andreabalducci : ci sono prerequisiti specifici per partecipare all'evento che vuoi vengano esplicitati nella descrizione evento?

**Comment by andreabalducci** [comment]
@ste8 passi tu i contatti a @Defkon1 per favore?
Per i prerequisiti nulla a parte apertura mentale :P

**Comment by Defkon1** [comment]
https://www.eventbrite.com/e/devmarche-stranger-streams-event-sourcing-senza-confini-tickets-40178415723

**Comment by nonno** [comment]
@Defkon1 confermi che è al Cowo Ancona e non al Cowo42? Perché da quanto avete commentato sopra sembrava vi foste accordati per il Cowo42. E' un errore o alla fine la fate di fronte al cinema?

**Comment by Defkon1** [comment]
confermo CoWo Ancona per maggiore capienza (c'è stato uno scambio di messaggi extra-github)

**Comment by ste8** [comment]
Video dell'evento: https://vimeo.com/246752355
Slide: https://www.slideshare.net/andreabalducci/stranger-streams-nstore-devmarche
