### ISSUE TITLE
Cooking ServiceFabric and Akka.Net together

### ISSUE THREAD

**Issue by melkio** [DevMarche/eventi#4]
Erlang, Elixir, Scala con Akka, solo per fare gli esempi piu' famosi, sono implementazioni di un modello matematico, formulato nel 1973, ma del tutto attuale: l'Actor Model. Utilizzato per sviluppare soluzioni "concorrenti e distribuite", il concetto di "attore" si sposa alla perfezione anche con il mondo del "cloud".
Nell'ecosistema .Net due delle implementazioni più conosciute sono Akka.Net e i ReliableActor di ServiceFabric. Perchè scegliere? Perchè non utilizzare il meglio dei due "mondi"?

**Comment by DGuidi** [comment]
molto interessante. a che formato pensavi? tipo giornata intera, mezza giornata, altro/specificare :)

**Comment by ste8** [comment]
pure Ale Giorgetti  accennava a del materiale che potrebbe portare a riguardo (actor model, ...). Si potrebbe valutare se fare un evento pomeridiano.

**Comment by melkio** [comment]
@DGuidi dipende da quanto tempo abbiamo a disposizione. Puo' essere una sessione o un mini-workshop

**Comment by DGuidi** [comment]
a sto punto potrebbe aver senso fare un pomeriggio e tirar dentro anche ale, se vuole...

**Comment by AGiorgetti** [comment]
Si, ma non prima di dicembre (sono un po' incasinato :D )

**Comment by ste8** [comment]
Ho pingato anche Stefano Del Furia, che a WPC quest'anno farà una sessione su questi temi: http://wpc2017.it/cms/it-IT/SpeakerPage?parameters%5B0%5D=55

**Comment by melkio** [comment]
La sessione (che ho in mente) prevede una comparazione "guidata" tra I ReliableActor di ServiceFabric e Akka.Net. Quindi la sessione e' in merge tra una sessione che introduce Akka, una sessione generale su ServiceFabric (reliable service/actor stateless/stateful) e come unire le due cose. 

Non che non voglia "avere" sessioni su Akka.Net in contemporanea ma si corre il rischio di avere un po' (quanto?) di sovrapposizione. Ovviamente parliamone

**Comment by ste8** [comment]
@melkio sì, immagino ci possa essere questo rischio, Potrebbe aver senso organizzare una call tra te, @AGiorgetti Stefano (ovviamente sempre che gli vada di fare il talk :) ... e vedere se e come si potrebbe impostare un evento con un filo conduttore?

**Comment by melkio** [comment]
Ha molto senso :)

**Comment by delfuria** [comment]
L'idea mi sembra buona, sono disponibile !!!

**Comment by AGiorgetti** [comment]
è un pezzo che non organizziamo un evento 'massiccio' in effetti...

**Comment by ste8** [comment]
un evento pomeridiano nella seconda metà di gennaio o inizi febbraio, come lo vedete?

**Comment by DGuidi** [comment]
rischia di andare in sovrapposizione con quello sql, a breve dovrei avere le date ufficiali

**Comment by DGuidi** [comment]
ops scusate, avevo chiuso la pull per errore :(  non me ne ero accorto per niente...

**Comment by LabInfoRosselli** [comment]
In linea teorica a me potrebbe andare bene qualsiasi giorno tra gennaio e febbraio tranne il lunedì e mercoledì (ma non tutti)  perchè ho degli impegni già fissati con la scuola.

**Comment by ste8** [comment]
c'è la possibilità di farlo nella seconda metà di febbraio, un venerdì potrebbe essere il giorno migliore? tipo venerdì 23 febbraio?

**Comment by LabInfoRosselli** [comment]
Al momento il 23/2 per me sarebbe OK !

**Comment by andrekiba** [comment]
Se fosse un intero pomeriggio in gennaio/febbraio farebbe molto piacere anche a me così da organizzarmi e poter venire

**Comment by melkio** [comment]
Febbraio al momento e' ok anche per me. Il venerdi un ottimo giorno

**Comment by DGuidi** [comment]
Solo per ricordarvi che venerdi due febbraio è in programma l'evento SQL+Linux. Ogni altro venerdi prima o dopo sarebbe perfetto.

**Comment by delfuria** [comment]
Magari vi interessa dare una occhiata a questo progetto di demo che ho portato a WPC, dove ho cercato di introdurre il modello e di "coprire" un po' tutti gli aspetti di base e non di Akka.NET 
https://github.com/delfuria/WPC2017-AKKA.NET

**Comment by ste8** [comment]
Video dell'evento: 
https://vimeo.com/album/5006034

Slide:
1. https://www.slideshare.net/StefanoDelFuria/akkanet-actor-model
2. https://www.slideshare.net/melkio/cooking-akkanet-and-azure-service-fabric-together
3. https://www.slideshare.net/giorgettialessandro/the-big-picture-integrating-buzzwords
