### ISSUE TITLE
Un framework sul framework: generare una SPA dinamicamente in Angular partendo da un backend .NET

### ISSUE THREAD

**Issue by apomic80** [DevMarche/eventi#5]
Avevamo la necessità di realizzare il pannello di amministrazione della nuova versione del nostro CMS in modo che fosse una SPA dinamica e pluggabile a partire dalle informazioni che arrivano dal back-end: abbiamo scelto Angular e abbiamo creato dei componenti che dinamicamente generano la UI sulla base dello schema JSON, generato dinamicamente a partire dalla classi del backend scritto in .NET. 

Ne è venuto fuori un prodotto, che abbiamo chiamato Raptor, e che sarà presto rilasciato su GitHub come progetto open source. L'idea è mostrare come spingere Angular e .NET per automatizzare la generazione della UI in un sistema a plug-in che gestisca operazioni CRUD con logica business collegata mediante eventi sottoscrivibili e quindi personalizzabili.

Si daranno per conosciute le basi dei framework Angular e .NET.

**Comment by Defkon1** [comment]
http://dev.marche.it/eventi/2018/11/06/angular-and-beyond-ancona-7-dicembre-2018/
