### ISSUE TITLE
SQL Server su Linux

### ISSUE THREAD

**Issue by ddominici** [DevMarche/eventi#6]
Questo l'abstract: "Fino a qualche anno fa era solo un pesce d'Aprile... Ora SQL Server 2017 è una realtà su alcune versioni di Linux e su container Docker. In questa sessione vedremo le principali caratteristiche, come si installa (con un occhio alle best practices di sempre...), come si gestisce (SSMS o VS Code) e qualche altra cosuccia su HA e SSIS..."

La data ipotetica potrebbe essere Gennaio 2018, presso la Facoltà di Ingegneria di Ancona o a scelta in uno dei soliti spazi dei coworking in zona Ancona. Vediamo in base alle iscrizioni...

**Comment by DGuidi** [comment]
domanda: facolta o coworking sono un vincolo? o era solo un'idea?

**Comment by ddominici** [comment]
No, solo per "prassi", ma se ci sono altre soluzioni possiamo parlarne...

**Comment by DGuidi** [comment]
Nella sede di pesaro di TeamSystem si potrebbe organizzare. L'interesse pare esserci, sto cercando di capire quale sala si potrebbe utilizzare e quali date indicative potrebbero esserci. Hai proposte in merito?
 Soprattutto sulla durata e sulla capienza...   
Sicuramente mi vien da dire che dovrebbe essere almeno mezza giornata e in orari "lavorativi", ovvero da lunedi a venerdi, mattina e/o pomeriggio.

**Comment by DGuidi** [comment]
entro metà novembre ne saprò di più

**Comment by ddominici** [comment]
Può andare. Mezza giornata solo su Linux è un po' troppo... Conta una sessione di un'ora e un quarto. Però si può fare una mezza giornata di presentazione delle novità di SQL 2017... 80-100 persone direi che è un target raggiungibile... Se invitano i loro clienti/partner anche di più...

**Comment by DGuidi** [comment]
l'idea mia è di quella di fare un evento community standard, poi si può pubblicizzare nei canali standard di devmarche, ma anche in quelli aziendali senza problemi. mezza giornata su sql 2017 e sql su linux secondo me sarebbe ottimo. ma come detto, a metà mese ti aggiorno sulla fattibilità del tutto, e anche sulle sale eventualmente utilizzabili.

**Comment by ste8** [comment]
direi una mezza giornata sulle novità di Sql Server 2017 sarebbe un'ottima cosa!

**Comment by DGuidi** [comment]
occhi ste alle label :) ancora di fatto non so niente di preciso e non ho nessuna certezza.  direi di non chiudere la porta verso altre persone che si vogliono fare avanti per organizzarla in altri posti, università o coworking compresi.

**Comment by nonno** [comment]
Ormai @DGuidi so' cavoli tui, grazie in anticipo per l'impegno :)

**Comment by pracucci** [comment]
In Spreaker, abbiamo ereditato un sistema legacy basato su SQL Server e stiamo valutando se migrarlo a Linux (non nel brevissimo termine). Mi interessa molto questo talk.

**Comment by DGuidi** [comment]
@ddominici ho avuto proprio adesso un ok ufficioso per una data qui in TeamSystem a Pesaro genericamente dopo metà gennaio.   ho chiesto un ok **ufficial*e* entro pochi giorni (spero per il 20 novembre ecco) in modo da mettere poi in moto la macchina organizzativa.  
Ho i tuoi contatti e direi che poi ci sentiremo in privato, aggiornando la issue github con le novità principali, ok?

**Comment by DGuidi** [comment]
ora ho l'ok ufficiale, entro breve spero di avere la data definitiva :)

**Comment by DGuidi** [comment]
la data quasi-ufficiale (manca solo la pubblicità) è **venerdi 2 febbraio**.   per l'organizzazione di altri eventi magari tenete che in quella data ci sarà l'evento SQL Server, grazie :)

**Comment by DGuidi** [comment]
aspetto abstract e poi la metto in calendario

**Comment by DGuidi** [comment]
domanda: assodato che si farà il due febbraio, quale è la data migliore per pubblicare il link all'iscrizione? prima o dopo le feste? 😁

**Comment by ste8** [comment]
prima lo fai, meglio è... in entrambi i casi, ti conviene fare dei post prima o dopo, tipo #savethedate o promemoria dell'agenda già pubblicata :)

**Comment by DGuidi** [comment]
ok grazie, lunedi mi ci metto

**Comment by DGuidi** [comment]
ho pubblicato l'evento su [eventbrite](https://www.eventbrite.com/e/sql-server-2017-tutte-le-novita-tickets-41377757988) anche se aspetto un pò prima di pubblicizzarlo... se vedete errori o segnalazione, per favore segnalatemelo :)

**Comment by DGuidi** [comment]
pubblicato su [facebook](https://www.facebook.com/groups/developermarche/permalink/1910675998972850/)

P.S: grazie @nonno  per la gestione dei tag :)

**Comment by DGuidi** [comment]
il video è disponibile [qui](https://vimeo.com/album/4969789/), grazie a stefano :)

**Comment by DGuidi** [comment]
[20180202 - SQL Server 2017.pdf](https://github.com/DevMarche/eventi/files/1716522/20180202.-.SQL.Server.2017.pdf)
appoggio le slides qui, a breve le rendo disponibili a tutti i partecipanti
