### ISSUE TITLE
ESP32, funzionamento e programmazione

### ISSUE THREAD

**Issue by guizzardi** [DevMarche/eventi#66]
Salve a tutti, rilancio quanto proposto mesi fà, ovvero un incontro/serata sull'ESP32 (sto scrivendo un libro per Sandit sull'argomento). Non solo come funziona una scheda basata sul microcontrollore ma, se può essere più interessante, come programmarlo con un po tutti i linguaggi (C/C++, Python, Rust, Go, ecc.) usando Arduino IDE e PlatformIO.

Tempistiche: per metà settembre in poi.

Ogni suggerimento è ben accetto!

**Comment by bgvsan** [comment]
Ciao, potremmo discuterne, dove ti piacerebbe puntare?
Vuoi parlare genericamente per permettere a tutti di cominciare da zero, sei orientato a rimanere al teorico o dimostrazione pratica?

**Comment by guizzardi** [comment]
E' possibile affrontare l'argomento sia da zero che da un livello più alto anche se nel secondo caso la platea dovrebbe già avere una certa conoscenza dei microcontroller e dell'ESP32 nello specifico. Magari si potrebbe partire da zero arrivando ad un buon livello velocemente senza troppo soffermarsi su ogni singolo aspetto, sia software che hardware. P.e. tralasciare configurazioni o settaggi di ambienti di sviluppo per arrivare subito a come utilizzare l'MQTT o altri servizi per raccogliere dati o interagire con altri device. Dipende molto anche dal tempo a disposizione. Oppure, si potrebbe realizzare direttamente un progetto per qualche tipo di lavoro, banalmente un sistema di raccolta dati ambientali, ecc...

**Comment by bgvsan** [comment]
Parlo per me, ma punterei o a qualcosa di avanzato, oppure a una sessione pratica con dispositivi alla mano dove tutti possano sperimentare. ( sono un po' un fanatico dei workshop )

L'idea di far lampeggiare un led , si fa tranquillamente con un tutorial online scaricando uno sketch di esempio, magari vediamo se ha senso alzare più il tiro.

L'idea di un mqtt potrebbe essere la buona strada , penso anche a sfruttare potenzialità multicore, o RTOS ( sono solo idee buttate lì ).

@ste8 Abbiamo qualcuno che mastica , che può dare suggerimenti a riguardo?

**Comment by ste8** [comment]
Anni fa c'era la community di Arduino delle Marche, tra le persone che la gestivano Marco Focanti.
Questo era il gruppo fb: https://www.facebook.com/groups/adamo.marche/
Può essere utile contattarli?

**Comment by bgvsan** [comment]
pensavo piu sul lato organizzativo dell'evento per stabilire cosa mettere per rendere interessante la cosa, ho esperienza diretta sui dispositivi, un po meno la realizzazione degli eventi.
vorrei evitare che sia troppo basico e allo stesso tempo evitare che sia troppo tecnico.

**Comment by guizzardi** [comment]
@ste8 La comunità su FB sembra abbandonata. Possiamo comunque pubblicare qualche cosa per vedere se c'è riscontro.

@bgvsan Facciamo 2 appuntamenti (troppi?), uno da zero alla raccolta dati su cloud o altro, e uno su progetti specifici e complessi magari con differenti linguaggi e ambienti di programmazione.

**Comment by bgvsan** [comment]
Bisognerebbe capire cosa interessa alle persone, per me potrebbe essere affascinante parlare nel dettaglio anche di come funziona l'architettura, ma non renderebbe appetibile la cosa al resto del mondo.
buttiamo sul tavolo tutto poi decideremo se dividere gli eventi, penso che dipenderà molto anche dal formato e orario.

**Comment by guizzardi** [comment]
Ok, tralasciamo l'approccio iniziale e concentriamoci su un progetto complesso (magari chi vuole partire da zero lo affronto singolarmente e fuori evento oppure lo accesso velocemente). Si potrebbe realizzare un progetto di domotica che comprenda diverse tecnologie, p.e. sistema di accessi, controlli remoti, luci, giardino, citofonia, ecc.
Possiamo coprire un po' tutto: wi-fi, bluetooth, web server, seriale, PWM, MQTT, segnali, componenti elettronici, ecc.

**Comment by ste8** [comment]
Evento svolto il 28 ottobre 2024 al FabLab di Falconara: https://dev.marche.it/eventi/2024/10/30/esp32-sblocca-il-potenziale-dei-tuoi-progetti-iot/
