### ISSUE TITLE
Unit Testing in an Angular 6+ Application

### ISSUE THREAD

**Issue by AGiorgetti** [DevMarche/eventi#8]
Testare una applicazione Angular non è sempre semplice ed immediato, soprattutto al crescere della complessità dell'applicazione stessa. 
Tuttavia è una pratica che non possiamo più permetterci di trascurare: è finito il tempo dei 'banali' data-entry! 
Conoscere le armi a nostra disposizione è fondamentale per ridurre al minimo i difetti presenti nelle applicazioni: diverse technologie, tools e test frameworks interagiscono e si integrano tra di loro a costituire un ambiente di testing stabile e ben definito.
Possiamo scegliere quali strumenti utilizzare a seconda della tipologia di test e dello scenario da verificare: dal singolo componente / direttiva, al servizio fino al testing dell'intero sistema. Vedremo come realizzare Unit Test in Angular utilizzando le utility messe a disposizione dal test framework, seguendo alcune best practice, affrontando diversi scenari ed evitando alcune trappole.

**Comment by williamverdolini** [comment]
Ciao, potremmo organizzare nella sede Loccioni (Angeli di Rosora). 

Il formato è quello del techbar vedo, giusto? Se pensate possa andar bene ci organizziamo per i vari dettagli. ok?

**Comment by DGuidi** [comment]
orario serale o pomeridiano?

**Comment by williamverdolini** [comment]
Serale è più facile da organizzare, non credo sia un vincolo però (dipende dal periodo e dalla durata).

**Comment by Defkon1** [comment]
ci sono novità su questo techbar?

**Comment by AGiorgetti** [comment]
Quando qualcuno lo vuole organizzare mi avverte un paio di settimane prima che devo trovare il tempo di aggiornare tutti i sample :D

**Comment by Defkon1** [comment]
è che non ho ben capito se @williamverdolini sta già organizzando la cosa...

**Comment by williamverdolini** [comment]
@Defkon1 la cosa la stavano seguendo dei colleghi, ma ad oggi prima della fine di giugno non riescono a seguire gli aspetti organizzativi, quindi se qualcuno vuole organizzare prima l'evento, non c'è problema

**Comment by Defkon1** [comment]
@AGiorgetti nella seconda settimana di maggio come sei messo?

**Comment by AGiorgetti** [comment]
Giovedì 10 potrebbe andare. generalmente Martedì e Giovedì sono i giorni migliori per me (altrimenti sono in palestra :D)

**Comment by Defkon1** [comment]
Per me giovedì 10 può andare... la accendiamo?

**Comment by Defkon1** [comment]
ping @AGiorgetti

**Comment by AGiorgetti** [comment]
Ciao, giornate incasinate... il 10 non riesco più scusa, giorni buoni: 17, 22, 24, 29 :D
prendiamone uno e via!!

**Comment by ste8** [comment]
@AGiorgetti sarebbe un workshop di una serata intera? 
se sì bene, altrimenti si può valutare se fare 1 ora questa sessione ed un'altra ora quest'altra https://github.com/DevMarche/eventi/issues/26
Può aver senso?
/cc @mazzcris

**Comment by AGiorgetti** [comment]
a correre si fa in 1 ora, ad andare piano e magari fare anche delle prove con un po' di codice live 2 ore+

**Comment by ste8** [comment]
ok, direi di fare le cose con calma e dedicargli il tempo necessario

**Comment by Defkon1** [comment]
ma quindi pensavi ad un formato rispetto al techbar, o nei tempi del techbar ci stiamo?

**Comment by AGiorgetti** [comment]
Techbar ci siamo secondo me, ci facciamo una serata chiacchierando su come fare un po' di test in angular

**Comment by Defkon1** [comment]
il 17 mi sa che mi è uscito un impiccio, mi orienterei verso il 22 se sei ancora disponibile...

**Comment by AGiorgetti** [comment]
yep bene per il 22, di norma per me vanno bene i Martedì ed i Giovedì

**Comment by AGiorgetti** [comment]
intanto ho aggiornato il titolo :D

**Comment by AGiorgetti** [comment]
mi sa che non confermiamo nemmeno il 22 :D, troppo vicino per organizzare e promuovere direi, per cui prendi un qualsiasi Martedì o Giovedì e fammi sapere.

**Comment by Defkon1** [comment]
scusa @AGiorgetti , è colpa mia, ma purtroppo sto aspettando di capire dalla FIP le date dei playoff che si devono giocare tra il 20/05 e il 02/06, altrimenti rischio di organizzare un evento a cui poi non posso partecipare...

se vogliamo mantenere il 22 bisogna che qualcuno mi sostituisce all'organizzazione, perché finché non esce il calendario definitivo rimango in bilico...

**Comment by AGiorgetti** [comment]
per me nessun problema, ho più tempo per rivedere ed aggiornare il tutto, lo faremo quando si potrà :)

**Comment by Defkon1** [comment]
https://www.eventbrite.it/e/biglietti-devmarche-unit-testing-in-angular-49842086021

**Comment by Defkon1** [comment]
Evento fatto, video della serata:

- Parte 1: https://vimeo.com/293833919
- Parte 2: https://vimeo.com/294136028
